### PR TITLE
Make loglevel adjustable

### PR DESCRIPTION
**Pull request by Apollon77**
add second (optional) init parameter to make loglevel adjustable.

I need that because when using your library in my project the console output is not ideal

### CODE REVIEW

**Comment by Apollon77** [comment]
... the alternative would be an exposed method to set the loglevel

**Comment by orlopau** [comment]
Looking good, thank you for the contribution :)

**Comment by Apollon77** [comment]
Yw

**Comment by Strobelix80** [comment]
Apollon77 and ds-wrapper? Looks like a step forward for ioBroker Adapter?

**Comment by Apollon77** [comment]
Do you use digitalstrom and iobroker? If you would be willing to beta test send me an email please. iobroker@fischer-ka.de

**Comment by Strobelix80** [comment]
Done. Waiting for your reply

**Comment by Apollon77** [comment]
@Strobelix80 got no email ...

**Comment by Apollon77** [comment]
@orlopau Could you please do a npm release with this change, thank you!

**Comment by Strobelix80** [comment]
@Apollon77 tried it once more. Please also check your spam

**Comment by orlopau** [comment]
@Apollon77 done

**Pull request merged**
