### PR TITLE
Add error handling for timeouts and special cases without response

### PR DESCRIPTION
**Pull request by Apollon77**

### CODE REVIEW

**Comment by orlopau** [comment]
Thanks, will release a new version soon.

**Comment by Apollon77** [comment]
Thank you!

**Comment by Apollon77** [comment]
Do you have any ETA for the new version?

**Comment by orlopau** [comment]
Probably tomorrow

**Comment by orlopau** [comment]
Published new version, 1.0.1

**Comment by Apollon77** [comment]
Thank you. Perfect timing ;-)

**Pull request merged**
